---
- name: "Jailkit | Download"
  get_url:
    url: http://olivier.sessink.nl/jailkit/jailkit-2.19.tar.gz
    dest: /tmp/jailkit-2.19.tar.gz

- name: "Jailkit | Unarchive"
  unarchive:
    src: /tmp/jailkit-2.19.tar.gz
    dest: /tmp/jailkit-2.19
    remote_src: yes

- name: "Jailkit | Installing jailkit 1/4"
  command: echo 5 > /tmp/jailkit-2.19/debian/compat 

- name: "Jailkit | Installing jailkit 2/4"
  command: ./tmp/jailkit-2.19/debian/rules binary 

- name: "Jailkit | Installing jailkit 3/4"
  command: dpkg -i /tmp/jailkit-2.19/jailkit_2.19-1_*.deb

- name: "Jailkit | Installing jailkit 4/4"
  command: rm /tmp/jailkit-2.19/jailkit_2.19
