---
# https://www.virtualmin.com/node/53969

- name: "Jailkit | Installing jailkit repository key"
  command: wget http://software2.virtualmin.com/lib/RPM-GPG-KEY-virtualmin-6 -O /tmp/RPM-GPG-KEY-virtualmin-6 | apt-key add /tmp/RPM-GPG-KEY-virtualmin-6

- name: "Jailkit | Add repository"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-xenial main
    - deb http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal main

