---
- name: "MySQL Secure | Set root Password"
  mysql_user: login_password={{ mysql_root_password }} check_implicit_admin=yes name=root host={{ item }} password={{ mysql_root_password }} state=present 
  with_items:
    - localhost
    - 127.0.0.1
    - ::1

- name: "MySQL Secure | Remove anonymous users"
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: "MySQL Secure Disallow root login remotely"
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: "MySQL Secure | Remove test database and access to it"
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: "MySQL Secure | Set the password authentication method in MariaDB to native"
  shell: echo "update mysql.user set plugin = 'mysql_native_password' where user='root';" | mysql -u root

- name: "MySQL Secure | Reload privilege tables"
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: "MySQL Secure | Add mysql_secure=yes to /etc/facts.conf"
  lineinfile:
    path: /etc/facts.conf
    state: present
    line: 'mysql_secure=yes'
