---
- name: "Roundcube | Configure roundcube /etc/roundcube/config.inc.php"
  template:
    src: roundcube.inc.php
    dest: /etc/roundcube/config.inc.php
  when: not ansible_check_mode

- name: "Roundcube | Configure roundcube /etc/apache2/conf-enabled/roundcube.conf"
  lineinfile:
    path: /etc/apache2/conf-enabled/roundcube.conf
    insertbefore: '<Directory /var/lib/roundcube/>'
    line: 'Alias /webmail /var/lib/roundcube'
  when: not ansible_check_mode
